# Generated by Django 4.0.1 on 2022-02-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.products')),
            ],
            options={
                'verbose_name': 'Cart-item',
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
