# Generated by Django 4.0 on 2022-02-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_brands_alter_products_category_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brands', verbose_name='Brand'),
        ),
    ]
