# Generated by Django 4.0.1 on 2022-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_products_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Product slug'),
        ),
    ]
