# Generated by Django 4.0.1 on 2022-02-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
