# Generated by Django 4.0.1 on 2022-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
