# Generated by Django 4.0.1 on 2022-02-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
