# Generated by Django 4.0.1 on 2022-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='empty_start',
            field=models.IntegerField(null=True),
        ),
    ]
