# Generated by Django 4.0.1 on 2022-02-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_reviews_creation_date_reviews_empty_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='empty_start',
            new_name='empty_stars',
        ),
    ]
