# Generated by Django 4.0.1 on 2022-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_empty_start_reviews_empty_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
