# Generated by Django 4.0.1 on 2022-02-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Old Price'),
        ),
    ]
