# Generated by Django 4.0.1 on 2022-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_products_rate_alter_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='empty',
            field=models.FloatField(default=0, verbose_name='Empty'),
        ),
    ]
