# Generated by Django 4.0.1 on 2022-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_products_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='empty',
            field=models.FloatField(default=5, verbose_name='Empty'),
        ),
    ]
