# Generated by Django 4.0.1 on 2022-02-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_products_wished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='wished',
        ),
    ]
