# Generated by Django 4.0.1 on 2022-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_newsletter_options_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=200, verbose_name='Specification')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='characteristics',
            field=models.ManyToManyField(to='main.Features'),
        ),
    ]
