# Generated by Django 4.0.1 on 2022-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_features_categories_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='specification',
            field=models.CharField(max_length=200, unique=True, verbose_name='Specification'),
        ),
    ]
